### ISSUE TITLE
Add rule no-bitwise

### ISSUE THREAD

**Issue by inverno** [SonarSource/SonarTS#123]
Currently available in TSLint core rules, but too noisy

**Comment by vilchik-elena** [comment]
We should decide either to include noisy implementation from tslint (no-bitwise) or do a smarter one (like in SonarJS). Note that even the one from SonarJS is not perfect.

**Comment by vilchik-elena** [comment]
https://jira.sonarsource.com/browse/RSPEC-1529

**Comment by saberduck** [comment]
https://github.com/SonarSource/SonarJS/pull/1901
