### ISSUE TITLE
Rule S3242: Function parameters should be declared with base types

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarTS#158]
Implements [RSPEC-3242](https://jira.sonarsource.com/browse/RSPEC-3242)

**Comment by vilchik-elena** [comment]
After implementing this rule it became obvious that its value is super low. Rule for sure should not be in recommended profile. This rule might help if developer **wants** to refactor code, but in general applying such generalization might even hurt in code maintainability and understandability.
I remove this rule from plugin and mark it as irrelevant for TS.
