### ISSUE TITLE
Support multiple tsconfig.json files

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#161]
One project might include several typescript modules, thus several `tsconfig.json` files. Current implementation requires to have `tsconfig.json` in the root directory of project, which is not the case for multi-module project.

In order to support it, we will do following:
1. Get full list of typescript files provided by SQ
2. Match for each of it a `tsconfig.json` file (by going up, until project root)
3. Group files by common `tsconfig.json`
4. For each group run rules providing each file and corresponding `tsconfig.json`

**Comment by karlo0** [comment]
Are multiple `tsconfig.json` files now supported? In my case I have subprojects with own `tsconfig.json` files. We are using SonarScanner CLI in Gitlab CI/CD and was wondering how to set up the scanner for multiple typescript subprojects.

**Comment by saberduck** [comment]
hello @karlo0 , this repository is no longer used. Please ask the question using our community forum here https://community.sonarsource.com/
