### ISSUE TITLE
Rule: Switch cases should end with an unconditional "break" statement

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#18]
Implements RSPEC-128

**Comment by stas-vilchik** [comment]
looks like it's covered by the `--noFallthroughCasesInSwitch` compiler option

**Comment by vilchik-elena** [comment]
Close as duplicate of TSLint core rule https://palantir.github.io/tslint/rules/no-switch-case-fall-through/ (probably implemented with TS compiler option)
