### ISSUE TITLE
Documentation only for logged in users?

### ISSUE THREAD

**Issue by tommueller** [SonarSource/SonarTS#186]
I am interested in using and testing this, but when I click the link to the documentation (https://docs.sonarqube.org/display/PLUG/SonarTS) provided in the README I have to enter user credentials. Why do I need to sign up to see the docs?

**Comment by vilchik-elena** [comment]
@tommueller sorry it's our fault. It is closed as it's WIP, we were going to open it as soon as SonarTS is released, but indeed it's useful during feedback period (which ends tomorrow). I'm gonna open it.
Thanks!

**Comment by tommueller** [comment]
Cheers

**Comment by tommueller** [comment]
Could you also open the page on HowTo include a coverage report? https://docs.sonarqube.org/pages/viewpage.action?pageId=9012575

**Comment by vilchik-elena** [comment]
@tommueller done!

**Comment by tommueller** [comment]
Cheers, works like a charm!
