### ISSUE TITLE
Possible deadlock in case of unconsumed errors in rule execution

### ISSUE THREAD

**Issue by inverno** [SonarSource/SonarTS#200]
The following line is likely the reason why some users have reported a hanging execution :
https://github.com/SonarSource/SonarTS-Plugin/blob/7efeb6a79839249e26f1358be6e85dea1e337b64/sonar-typescript-plugin/src/main/java/org/sonar/plugin/typescript/ExternalTypescriptSensor.java#L219

This might result in a deadlock in case the external process is waiting for the plugin to consume its error stream.

**Comment by inverno** [comment]
A hanging problem was reported in a project that seems to have had the characteristic of being an Angular 4 project with multiple *.module.ts and *.router.ts files in the same project folder. It might be worth testing this before and after fixing this.

**Comment by vilchik-elena** [comment]
Fixed by #209
