### ISSUE TITLE
Scanner hangs forever without any error message

### ISSUE THREAD

**Issue by MhdTlb** [SonarSource/SonarTS#205]
I'm trying to use SonarTS to scan my project.

 After running the cmd command `sonar-scanner` in my project, every thing seems to work fine.
But at this point:

`INFO: Running rule analysis for 'C:\Sonar\...\TS\Scripts\tsconfig.json' with 110 files`, the scanner just stop working and I'm been waiting for hours without any error message.

The weired thing is if I remove specific set of files, SonarTS works fine.

**Comment by vilchik-elena** [comment]
@MhdTlb Hi, thanks for reporting! It's kind of a known issue (see #200). It would be useful for us if you could provide a project reproducing your problem.

**Comment by MhdTlb** [comment]
Initially, I did a successful scan with one TS file that has 200 line of code. But I got the above error as soon as I:

1.  Add more lines to one file (> 220 line) and file size was around 4 KB
or
2. Include more files to the scan (> 6 files)

**Comment by inverno** [comment]
@MhdTlb thanks a lot for the info, but we are already using SonarTS to scan dozens of projects with thousands of files, with files sizes ranging from zero lines to many thousand lines, and we don't encounter this hanging problem. Maybe #200 is going to solve your issue, but we can't tell for sure without a project from you that reproduces the issue and that we can use in our tests.

**Comment by inverno** [comment]
Probably Fixed by #200
@MhdTlb if you can, try the RC we just published : https://github.com/SonarSource/SonarTS/releases/tag/1.1.0-RC1
