### ISSUE TITLE
All TS files are ignored if project does not have tsconfig file

### ISSUE THREAD

**Issue by MhdTlb** [SonarSource/SonarTS#215]
It would be nice if SonarTS supports projects without tsconfig file. 
In my case, I'm using Visual Studio and I don't need to setup a tsconfig at all.
If I run SonarTS for my project, I can see in the console that all my ts files are ignored with this error: 

> ERROR: No tsconfig.json file found for D:/Agent/_work/34/s/.../Home.ts (looking up the directories tree). This file will not be analyzed.

Is there a way to ignore checking for tsconfig file or I have to add that file to my project?

**Comment by vilchik-elena** [comment]
@MhdTlb Thanks for the feedback! Indeed we considering such feature in our next version(s).
Could you tell as well how do you configure typescript without tsconfig in VS?

**Comment by dantran** [comment]
or project does not use tsconfig.json but by another name.  I search thru the code.  looks like tsconfig.json is hardcoded.

**Comment by captainjono** [comment]
-we use an external tool to call tsc via its api
-we have a solution with many typescript projects
-would be nice to have a command line option or similiar to point to a single tsconfig of our choosing to use across all projects.

**Comment by vilchik-elena** [comment]
@captainjono Can you share the name of this external tool?

**Comment by captainjono** [comment]
@vilchik-elena Its an internal tool built by our company to package our software - very similiar to something like webpack. But yes, we dont have any tsconfig.json at all. All settings are built into the tool and tsc is called via its API. Its possible for me to say, add a single tsconfig to the build process and allow sonarTS to reference it, but we have over 100 projects so i would have to create a script to copy this tsconfig into all of them which im probably going todo in the meantime..

**Comment by vilchik-elena** [comment]
@captainjono thanks a lot for these insights, our team will think how better to treat cases like yours. And one more question, do you have node_modules with typescript package in each project?

**Comment by captainjono** [comment]
Umm no we dont - we dont even use node_modules..

**Comment by vilchik-elena** [comment]
See #444

**Comment by jmurekezi** [comment]
is there a solution for this? all my ts files are being ignored by sonar and having an angular project means this is a big issue for us
