### ISSUE TITLE
Mysterious FPs in no-accessor-field-mismatch

### ISSUE THREAD

**Issue by inverno** [SonarSource/SonarTS#245]
For unknown reasons `no-accessor-field-mismatch` raises three FPs in ruling:
`src/vscode/src/vs/platform/telemetry/common/telemetryUtils.ts: 43`
`src/vscode/src/vs/editor/contrib/codelens/browser/codelens.ts: 165`
` src/vscode/src/vs/workbench/parts/markers/common/markersModel.ts: 100`

**Comment by vilchik-elena** [comment]
duplicates #476
