### ISSUE TITLE
Support for multi-module Gradle projects? 

### ISSUE THREAD

**Issue by hosszubalazs** [SonarSource/SonarTS#259]
Hi!

I'm currently using the Gradle Plugin for a multi module project setup
https://plugins.gradle.org/plugin/org.sonarqube

Some of the modules contain TypeScript code, and I'd like to introduce SonarTS analyzis for these. _node_ and _typescript_ is not installed globally.

Caused by: java.lang.IllegalStateException: Failed to run external process `node /local/projects/path/to/project/build/sonar/name-of-suproject-with-typescript/sonarts-bundle/node_modules/tslint-sonarts/bin/tsrunner`

From the documentation:
https://docs.sonarqube.org/display/PLUG/SonarTS
"If missing, install node.js current on the machine" 

I do not plan to have a project / machine global node available on the path. Different modules might need different versions, so they use their own version. Is this use-case supported with SonarTS 1.1? I understand 1.1 introduces support for multi-module setup, but not sure in detail how it is expected to work.

Perhaps this issue relates to https://github.com/SonarSource/SonarTS/issues/203

If each module could set it's path for Sonar, where it's node and node_modules are stored, that would probably work out. Is this supported / planned? 

Environment:
Using SonarTS 1.1.0.1079 
SonarQube 5.6.6 LTS
Gradle Plugin 2.5

Thanks and cheers,
Balázs

**Comment by vilchik-elena** [comment]
hi @hosszubalazs,

Indeed, you are facing a use-case not supported by SonarTS 1.1, as it relies on node being installed globally. Adding property to set up location of node would make work for you, but do you really want one more property for `node_modules`? Currently we need `node_modules` containing `typescript` be somewhere inside module dir.

**Comment by hosszubalazs** [comment]
Hey @vilchik-elena !

**Comment by hosszubalazs** [comment]
Hey @vilchik-elena,

Thanks for your quick response, it is appreciated!

> Adding property to set up location of node would make work for you, but do you really want one more property for node_modules?
I see from the linked issues the node path is a recurring issue. Do you have plans / progress in this direction? 
If node_modules is found inside the modules then it should be fine.

> Currently we need node_modules containing typescript be somewhere inside module dir.
This is already fulfilled, each modules contains ``node_modules`` with ``typescript`` in it.

ps. sry closed by accident :)

**Comment by vilchik-elena** [comment]
@hosszubalazs Thanks for answering, and looks like #202 will perfectly fix your problem. So please track #202 now, I will close this one.
#202 should be addressed in next version already.

**Comment by hosszubalazs** [comment]
Perfect thanks!
