### ISSUE TITLE
Rename repository to align to SonarSource standard

### ISSUE THREAD

**Issue by hosszubalazs** [SonarSource/SonarTS#26]
This repository is called SonarTS, which seems unusual. Language plugin namings usually follow the kebab-case style:
sonar-java
sonar-css
sonar-javascript

Rename the repository to align to the common style. Suggestion:
**sonar-typescript**

**Comment by stas-vilchik** [comment]
The thing is that the SonarSource's product name is SonarTS. This is our company's standard. Other repositories should be renamed soon.

**Comment by hosszubalazs** [comment]
Thanks for the answer!
