### ISSUE TITLE
Clarify toSonarLine with a comment

### ISSUE THREAD

**Issue by hosszubalazs** [SonarSource/SonarTS#260]
The currently only method in sonar-utils is a bit mysterious. Why offset the line number with +1 to make it a "Sonar line" ?  Please improve the code with a comment.

https://github.com/SonarSource/SonarTS/blob/master/sonarts-core/src/runner/sonar-utils.ts

**Comment by vilchik-elena** [comment]
@hosszubalazs Indeed, may be a bit confusing. The thing is that sonar lines are 1 based (numeration starts from 1) and TS lines are 0 based. That's why this conversion happens.

**Comment by hosszubalazs** [comment]
Hey @vilchik-elena !

Thanks for the quick response!

I opened the following pull-request :  #261

**Comment by vilchik-elena** [comment]
@hosszubalazs thanks! merged
