### ISSUE TITLE
Create automated integration test for tslint-sonarts

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#282]
We should have automated tests, verifying that SonarTS works correctly as TSLint extension (https://www.npmjs.com/package/tslint-sonarts)

**Comment by jbarop** [comment]
`tslint` can be called with the `--out` option to output the violations into file. It would be nice if SonarTS could be configured to pick up such a file. For example from a previous build step.

**Comment by vilchik-elena** [comment]
@jbarop I'm afraid it's out of scope of SonarTS. Currently it embeds some TSLint rules, but if you need other rules, first, you could share which ones are you missing, second you probably could you community TS plugin

**Comment by jbarop** [comment]
I think I misunderstood this ticket. I thought it was about adding all existing tslint rules to SonarTS. But I think it is about testing.

**Comment by vilchik-elena** [comment]
@jbarop indeed:) Sorry for missing description

**Comment by inverno** [comment]
@jbarop yes, I'll change the title again to make it more obvious
