### ISSUE TITLE
Add TypeScript global

### ISSUE THREAD

**Issue by kryzhmanov** [SonarSource/SonarTS#313]
When SQ scanning project, we have next issue "ERROR: No TypeScript compiler found in your project, analysis of typescript files is aborted". TypeScript installed global, but I guess SQ work just with local installed TypeScript. Could you please add opportunity in plugin to work with global TypeScript.

**Comment by vulitin** [comment]
Oh, I have this issue too, if you will add this feature it will be very useful.

**Comment by vilchik-elena** [comment]
This is fixed already by #258. It would be useful if you could test release candidate (should be available this Friday).
