### ISSUE TITLE
Deprecated and method overloading

### ISSUE THREAD

**Issue by RickHoving** [SonarSource/SonarTS#331]
**I want to report a bug.**

**SonarTS version:** 1.1 build 1079<br>
**Node.js version:** 8.2.1<br>
**TypeScript version:** 2.6.1<br>

**SonarQube version:** 6.6 build 32724<br>

**Rule key:** Deprecated APIs should not be used

**Reproducer** 
Include package moment (version 2.19.2)
In the dts of moment there is the following part of the interface of Moment
```
add(amount?: DurationInputArg1, unit?: DurationInputArg2): Moment;
/**
* @deprecated reverse syntax
*/
add(unit: unitOfTime.DurationConstructor, amount: number|string): Moment;
```

When calling this add function like this I get the code smell add is deprecated: reverse syntax
`moment.add(1, 'month');`

**Expected behavior**
I expect the code smell to appear when calling moment like this: `moment.add( 'month', 1);` not like `moment.add(1, 'month');`

**Comment by vilchik-elena** [comment]
@RickHoving try with SonarTS 1.2, for me it fixed your problem.

**Comment by RickHoving** [comment]
Thanks @vilchik-elena I updated to 1.2 and that fixed the problem!
