### ISSUE TITLE
Analysis halts completely if node bin not found

### ISSUE THREAD

**Issue by hosszubalazs** [SonarSource/SonarTS#339]
**I want to report a bug.**
**SonarTS version:** 1.2<br>
**Node.js version:** 6.10<br>
**TypeScript version:** 2.4<br>
**SonarQube version:** 5.6<br>

**Reproducer** 
Run a Gradle analysis on a project with .ts code, where node is not on the PATH and sonar.typescript.node is not set. The Gradle build fails. The analysis is not completed, no report is uploaded.

**Logs**
```
Caused by: java.lang.IllegalStateException: Failed to run external process `node /local/projects/path/to/my/project/sonarts-bundle/node_modules/tslint-sonarts/bin/tsrunner`. Run with -X for more information

Caused by: java.io.IOException: Cannot run program "node": error=2, No such file or directory
```

**Expected behavior**
If node cannot be found (neither available globally nor the bin path set manually), I'd expect for the analysis to gracefully skip the TypeScript analysis. I see the current behaviour an issue in the following scenario:
Some of the projects using my Sonar server might have TypeScript code. If I install the TypeScript plugin right now, analysis will start breaking on these projects, with no changes from their point of view. I need to proactively set the node path on all of them before any projects can start using the plugin.
I'd much prefer if analysis would still continue and succeed, and only log the issue.

What do you think?

P.s. Thanks a lot for fixing #202 !

**Comment by vilchik-elena** [comment]
Makes sense to me, thanks for feedback!
