### ISSUE TITLE
Plans for Angular rules? 

### ISSUE THREAD

**Issue by hosszubalazs** [SonarSource/SonarTS#341]
**I want to request a feature.**
Do you plan to add rules supporting AngularJS ?  
In general, is framework based rules in plan for SonarTS?

Codelyzer for example supports Angular specific rules to be integrated into tslint. It would be great to have similar functionality available as part of the Sonar report.

I understand with SonarJS support for Vue was taken into consideration, but perhaps no Vue specific rules.
https://www.sonarsource.com/resources/product-news/news.html#sonarjs-3.1

**Comment by inverno** [comment]
@hosszubalazs indeed we added Vue-files support to SonarJS, not vue-specific rules. The goal is to be able to apply framework-neutral rules wherever JS code appears.
For SonarTS we are indeed discussing either embedding existing framework-specific tslint extensions (like Codelyzer's) and/or developing framework-specific rules ourselves. If and when this becomes more concrete you'll see it popping up in GitHub issues.

**Comment by hosszubalazs** [comment]
Thanks for the response! I'll keep an eye out. :)

**Comment by philipooo** [comment]
I would like to see the Codelyzer rules in SonarQube too. Or a way too import the results of an existing tslint run like in https://github.com/Pablissimo/SonarTsPlugin

**Comment by stas-vilchik** [comment]
@philipooo good news, we've just started working on the idea to import rules from external linters. No insights for the time being, but stay tuned! 😉

**Comment by philipooo** [comment]
@stas-vilchik Yeah, thats awesome news, thank you. I`ll say tuned!

**Comment by rrambaud** [comment]
+1 feature very much needed

**Comment by rrambaud** [comment]
any news on that project ?

**Comment by vilchik-elena** [comment]
@rrambaud See #610
