### ISSUE TITLE
Integrate all rules from tslint

### ISSUE THREAD

**Issue by jbarop** [SonarSource/SonarTS#344]
In a project we're using `tslint` to check for some gotchas.

While SonarTS adds more useful rules, it would also be great to visualize the existing rules/violations  from `tslint`.

**Comment by inverno** [comment]
@jbarop did you try adding https://www.npmjs.com/package/tslint-sonarts to your tslint setup?

**Comment by stas-vilchik** [comment]
I'm closing this issue for housekeeping reasons.

**Comment by mkp05** [comment]
@inverno but it's not about having SonarTS rules in TSLint, but having TSlint issues also visible on Sonar. To have Single-Source-Of-Truth with all issues in the code. Without that you have to manually use tslint locally and this plugin on Sonar. For bigger teams it's impossible to force all members to use and fix issues reported by TSlint when they can do it only locally...

**Comment by vilchik-elena** [comment]
@mkp05 This should be available in the middle term (https://jira.sonarsource.com/browse/MMF-1212)

**Comment by mkp05** [comment]
@vilchik-elena glad to hear that!
