### ISSUE TITLE
Rule: Functions should use "return" consistently

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#35]
Implements  RSPEC-3801
```
function foo(p: number) { // Noncompliant, function can implicitly return undefined 
  if (p > 0) {
    return 43;
  }
}

```

**Comment by inverno** [comment]
In fact, this rule might be of very little uses, thanks to TypeScript's type inference and the union types (number | undefined). The only case where it might still fit is when the function explicitly declares "any" as return type.
