### ISSUE TITLE
Review isEqualSymbolicValues

### ISSUE THREAD

**Issue by michalb-sonar** [SonarSource/SonarTS#355]
It reports `true` for `x` and `""` but is should not. See https://github.com/SonarSource/SonarTS/blob/46ef30620465f38456def53ce3d3116256d39559/sonarts-core/src/se/symbolicValues.ts#L64-L65

```
function foo(x: string) {
  if (x === "") {
  }
}
```

**Comment by vilchik-elena** [comment]
Closing as we don't want to invest in DFA
