### ISSUE TITLE
Warnings during processing LCOV report

### ISSUE THREAD

**Issue by Hamloux** [SonarSource/SonarTS#362]
Currently I get a lot of warn messages when running the analysis on our project. The error message goes like that:
Problem during processing LCOV report: can't save DA data for line X (Line with number X doesn't belong to file path/to/file.ts)

[WARNING] Problem during processing LCOV report: can't save DA data for line X of coverage report file (java.lang.IllegalArgumentException: Line with number X doesn't belong to file path/to/file.ts).

This happens during analyse where the file use import.

**SonarTS version:** 1.2.0.1484
**Node.js version:** 8.9.3
**TypeScript version:** 2.6.2

**SonarQube version:** 6.7

**Reproducer** 
```
Line 1 : // minimal reproducer if relevant
Line 2 : import {XXX} from "XXX"; //contains 2 lines for exemple
Line 3 : console.log("Hello, world"); 
```
We will have the warning 
[WARNING] Problem during processing LCOV report: can't save DA data for line X of coverage report file (java.lang.IllegalArgumentException: Line with number 4 doesn't belong to file path/to/file.ts).

as the : console.log("Hello, world");  will be considered is on the line 4

**Comment by stas-vilchik** [comment]
Could you copy your LCOV report for the reproducer please?

If it actually mentions the line 4 which doesn't exist in the reproducer, then the report is wrong.

**Comment by stas-vilchik** [comment]
I'm closing this issue for housekeeping reasons.
