### ISSUE TITLE
Prerequisite for NodeJS invalid

### ISSUE THREAD

**Issue by nielsnoorlander** [SonarSource/SonarTS#432]
**I want to report a bug.**
The current prerequisite of the NodeJS version for SonarTS 1.4 seems no longer valid.

**SonarTS version:** 1.4<br>
**Node.js version:** 6.12.3<br>
**SonarQube version:** 6.7.1<br>

**Reproducer** 
Reproducable with the SonarTS example projects
**Logs**
```
ERROR: /projectpath/.sonar/sonarts-bundle/node_modules/tslint-sonarts/lib/runner/sonarUtils.js:17
ERROR:         Object.entries(element).forEach(([key, value]) => {
ERROR:                ^
ERROR: 
ERROR: TypeError: Object.entries is not a function
ERROR:     at data.forEach (/projectpath/.sonar/sonarts-bundle/node_modules/tslint-sonarts/lib/runner/sonarUtils.js:17:16)
ERROR:     at Array.forEach (native)
ERROR:     at Object.stringifyToStream (/projectpath/.sonar/sonarts-bundle/node_modules/tslint-sonarts/lib/runner/sonarUtils.js:14:10)
ERROR:     at Socket.process.stdin.on (/projectpath/.sonar/sonarts-bundle/node_modules/tslint-sonarts/lib/runner/tsrunner.js:33:18)
ERROR:     at emitNone (events.js:91:20)
ERROR:     at Socket.emit (events.js:185:7)
ERROR:     at endReadableNT (_stream_readable.js:974:12)
ERROR:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
ERROR:     at process._tickCallback (internal/process/next_tick.js:104:9)
```

**I want to provide the following feedback.**
Upgrading to the latest NodeJS 8.x version solved the problem.

**Comment by ncooper09** [comment]
I can confirm this bug, though it's really an error in the documentation.

We saw the actual bug when we were on Node 6.(something.something). We switched to Node 8.9.4, and the issue was resolved.

We are on SonarTS 1.4 and SonarQube 6.7.1.

**Comment by vilchik-elena** [comment]
Thanks for reporting! I've added it to the bug fix milestone
Feel free to provide a PR

**Comment by vilchik-elena** [comment]
Bug fix release is done https://github.com/SonarSource/SonarTS/releases/tag/1.4.1.1991. Should be available in update center shortly
