### ISSUE TITLE
No valid rules have been specified

### ISSUE THREAD

**Issue by UiJo** [SonarSource/SonarTS#437]
**I want to report a bug.**

**SonarTS version:** 1.4.1<br>
**Node.js version:** v8.5.0<br>
**TypeScript version:** 2.4.2<br>
**TSLint version:** 5.7.0 <br>

**Reproducer** 
The plugin should use the already generated issues.json and coverage.lcov.info files.
Configuration:
```
sonar.typescript.tslint.outputPath=issues.json
sonar.typescript.lcov.reportPaths=coverage.lcov.info
sonar.typescript.node=/node
```

**Logs**
```
3:57.827 TypeScript compiler is found in this directory D:\platform-hub\hub-user-interface\node_modules
3:57.827 It will be used for analysis of typescript files
3:57.828 Deploying bundle from `/sonarts-bundle.zip` to `D:\platform-hub\hub-user-interface\target\sonar`
3:59.472 Checking node version
3:59.522 Using Node.js v8.5.0
3:59.533 Analyzing 127 typescript file(s) with the following configuration file D:\platform-hub\hub-user-interface\tsconfig.json
3:59.534 Setting 'NODE_PATH' to D:\platform-hub\hub-user-interface\node_modules
3:59.534 Starting external process `D:\platform-hub\hub-user-interface/node/node --max-old-space-size=2048 D:\platform-hub\hub-user-interface\target\sonar\sonarts-bundle\node_modules\tslint-sonarts\b

4:05.803 No valid rules have been specified
```

**Expected behavior**
no error in log

**Comment by vilchik-elena** [comment]
`sonar.typescript.tslint.outputPath` is property of https://github.com/Pablissimo/SonarTsPlugin
SonarTS doesn't use `issues.json`.
Do you have any rules activated in SonarQube for your TS project?

**Comment by UiJo** [comment]
Hi @vilchik-elena, correct, we used Pablissimo plugin before, which is why the confusion.
But now we use SonarTs plugin.
So: 
Rules are configured in the tslint files in my project. 
I need Sonar to use exactly those rules (as some changes were required).
Is there any property I can use in the plugin settings for this?

**Comment by vilchik-elena** [comment]
@UiJo No, SonarTS only allows configuring rules in SQ profile.

**Comment by UiJo** [comment]
@vilchik-elena : Thank you, I configured the rules in SQ profile (Sonar) and it works now.
I will try to use the npm library `tslint-sonarts` (extend the tslint rules with this ones)  in my project, in order to have same results on my machine  and on SonarQube

**Comment by vilchik-elena** [comment]
@UiJo fyi support of SonarTS in SonarLint (for VSCode in first place) should be available soon

**Comment by Aziaev** [comment]
No valid rules have been specified I have same issue

**Comment by vilchik-elena** [comment]
@Aziaev Have you tried to activate rules?

**Comment by Aziaev** [comment]
@vilchik-elena 
Are they activated by default?
This is my sonar props:
```sonar.projectName=FB-foo-bar-pl
sonar.projectKey=foo-bar-pl
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8
sonar.sources=app
sonar.exclusions=**/*.test.ts,container.tsx,**/initial-state.ts,**/interfaces.tsx,**/processes*.tsx,**/container.tsx,constants.ts,rm/helpers,rm/index,schemas.ts,**/styled.tsx,**/*.scss.d.ts,**/validation-schema.ts,**/*.view.tsx

sonar.ts.coverage.lcovReportPath=coverage\lcov-report\lcov.info
sonar.ts.tslint.projectPath=app
sonar.ts.tslint.configPath=tslint.json
```

**Comment by vilchik-elena** [comment]
@Aziaev They are activated by default
To check the rules being activated checkout rule profile associated to your project in SonarQube UI

**Comment by vilchik-elena** [comment]
@Aziaev FYI last 3 properties are from https://github.com/Pablissimo/SonarTsPlugin, not SonarTS

**Comment by Aziaev** [comment]
I have had an issue in sonar-project.properties
my report path was:
`sonar.ts.lcov.reportPath=coverage/lcov.info`

After changing it to 
`sonar.typescript.lcov.reportPaths=coverage/lcov.info `
Issue was resolved
