### ISSUE TITLE
Support missing tsconfig

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#444]

**Comment by captainjono** [comment]
is there a discussion about this? i need this feature and was wondering when it was coming?

**Comment by vilchik-elena** [comment]
@captainjono Can't tell you any exact dates, but the fact that you raise your point really matters :) Thanks

**Comment by saberduck** [comment]
Also import of issues from external analyzers should work without tsconfig. See this discussion on community forum https://community.sonarsource.com/t/importing-eslint-into-sonarqube/544/6
