### ISSUE TITLE
SonarLint support plans?

### ISSUE THREAD

**Issue by hosszubalazs** [SonarSource/SonarTS#457]
**I want to request a feature.**
Hey SonarTS team!

I'd like to inquire about plans for SonarLint support.

I understand support for VSCode is ongoing: MMF-1135
Do you have an ETA for this?
Do you plan to support other IDEs like IntelliJ? What is the priority on this?

Thanks and cheers,
Balázs

**Comment by vilchik-elena** [comment]
Hello @hosszubalazs! thanks for the interest:)
For VSCode we hope to finish this week, and for IntelliJ we don't have any particular plans, but it should be done pretty soon.

**Comment by hosszubalazs** [comment]
Thanks a lot for the quick answer! I'll keep an eye on the issues board, good luck with the progress. :)
