### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by stas-vilchik** [SonarSource/SonarTS#46]
- [x] finish README.md
- [x] add rule docs
- [x] test with different ts & tslint versions -> peer dep is added for tslint@^5.1.0 (which implicitly forces supported typescript version)
- [x] and .npmignore
- [x] add prepublish script to compile the project

For next release
- [ ] add CONTRIBUTING.md
- [ ] add CHANGELOG.md

**Comment by vilchik-elena** [comment]
Fixed with #55
