### ISSUE TITLE
FP S4275/no-accessor-field-mismatch

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#476]
![image](https://user-images.githubusercontent.com/10108186/35395230-166820d6-01ea-11e8-9c38-ff6b98c0af87.png)
https://github.com/Microsoft/vscode/blob/e5808be148c60f3a9aac27fece7eff1fa21a0264/src/vs/workbench/parts/markers/common/markersModel.ts#L102-L104

**Comment by PomanoB** [comment]
Another example:
```TypeScript
class Color
{
    public static readonly Red: Color = new Color();

    private readonly red: number;

    public getRed(): number // error noAccessorFieldMismatch: Refactor this getter so that it actually refers to the property 'Red'
    {
        return this.red;
    }
}
```
