### ISSUE TITLE
Support SonarTS in SonarLint for IntelliJ IDEA

### ISSUE THREAD

**Issue by hosszubalazs** [SonarSource/SonarTS#575]
**I want to request a feature.**
Dear SonarTS Team!

Please add support for TypeScript analysis into the IntelliJ IDEA plugin! it would be great to get the real-time feedback in other tools besides VS Code.

Thanks for considering,
Balázs

**Comment by saberduck** [comment]
This is definitely something we have in plan, but I can't yet provide the concrete timeframe. Stay tuned :-)

**Comment by vilchik-elena** [comment]
Ticket to follow https://jira.sonarsource.com/browse/SLI-263

**Comment by christophelevis** [comment]
@hosszubalazs Can you please tell us more about your use-case?
Do you also already use SonarTS with TSLint? If it's the case, what do you expect from the support for SonarTS in SonarLint?

**Comment by tzoratto** [comment]
@christophelevis In connected mode with SonarQube server the support for SonarTS in sonarLint would be great to keep all the rules-related configuration in SonarQube only

**Comment by jblievremont** [comment]
For your information, SonarLint [now supports analysis of TypeScript](https://community.sonarsource.com/t/sonarlint-can-now-analyze-typescript-in-jetbrains-ides/22839) in JetBrains IDEs, including IntelliJ IDEA, WebStorm and PHPStorm.
