### ISSUE TITLE
Update in documentation test/coverage section

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#579]
We should be more explicit on the way unit test reports should be imported (inspired by #561)

**Comment by saberduck** [comment]
I updated documentation on confluence https://docs.sonarqube.org/display/PLUG/TypeScript+Test+Execution+and+Coverage+Results+Import

And also included configuration for Jest on the example project https://github.com/SonarSource/SonarTS-example/tree/master/example1

**Comment by vilchik-elena** [comment]
lgtm
