### ISSUE TITLE
Scanner should not need to be install on the CI but should come as a dependency

### ISSUE THREAD

**Issue by tebeco** [SonarSource/SonarTS#608]
**I have no idea is this is a feature or a bug**

**SonarTS version:** plugin inside Sonar ? the one shipped with Sonar 7.0<br>
**Node.js version:** 8.x<br>
**TypeScript version:** 2.6<br>

**SonarQube version:** 7.0<br>
**SonarLint version and used IDE:** Why would i want to depend on any idea ?<br>

**Expected behavior**
after running :

```
npm install
npm build
npm test
```

I expect data to be on the Sonar server, for that i need to run some analysis ...
we already have a subtask of `npm test` that generate the `lcov` file

the issue is that so far our build agent need to have the `sonar-runner` (need to use the scaner) installed in the PATH and run a bat file

At least for C# stuff there's no need of that ... it is shipped via nuget dependency so repository ship what is needed as a package

what is the way of doing so for typescript stuff ?

**Comment by stas-vilchik** [comment]
You might want to use the [sonarqube-scanner](https://www.npmjs.com/package/sonarqube-scanner) which is a npm package wrapping `sonar-scanner` and providing the cli and the js api.

**Comment by tebeco** [comment]
hummmm thx a lot for the quick answer
that was my first guess
o think i looked for `runner` i forgot it was renamed `scanner` and found nothing my bad

will check that tomorrow
