### ISSUE TITLE
Add import of tslint issues report

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#610]
Thanks to https://jira.sonarsource.com/browse/MMF-1212 we can add support for import of issues from third-party tools. A new property holding tslint issue report should be added.
Note that feature is available only with SQ 7.2 (should be released in mid June) and on [SonarCloud](https://about.sonarcloud.io/)

**Comment by vilchik-elena** [comment]
Note that issues from tslint report for rules which are activated in SQ are filtered out

**Comment by vilchik-elena** [comment]
https://docs.sonarqube.org/display/PLUG/Importing+TSLint+issues+for+TypeScript+files

**Comment by Tiberriver256** [comment]
Is there an updated link for the docs on this?

**Comment by vilchik-elena** [comment]
@Tiberriver256 check here https://docs.sonarqube.org/latest/analysis/external-issues/
