### ISSUE TITLE
Allow exception for constructors for parameters-max-number 

### ISSUE THREAD

**Issue by enko** [SonarSource/SonarTS#651]
**I want to provide the following feedback.**

**Rule key:** parameters-max-number

When using Angular Dependency Injection all injected tokens are passed as values of the constructor. For this case it would be great to have an exception.

I have set `parameters-max-number` to 7 but I got 9 from DI:

```typescript
    public constructor(
        private store: Store,
        private scuttlebot: ScuttlebotService,
        private electron: ElectronService,
        private router: Router,
        private helper: HelperService,
        public elementRef: ElementRef,
        private _hotkeysService: HotkeysService,
        private _scrollService: ScrollToService,
        private changeDetectorRef: ChangeDetectorRef,
    ) { }
```
Possibly there can be more in more complex situations and there is no easy way I can reduce parameter in this case.

**Comment by andrea-guarino-sonarsource** [comment]
Hi @enko,

Thanks for your feedback.
In order to add this exception, we would need to to know when a parameter comes from DI.
Is it sufficient to check for its type, that has to be decorated with `@Injectable()`?

**Comment by enko** [comment]
Hey @andrea-guarino-sonarsource 

These are the criteria I can think of:

* It has to be the constructor
* A parameter must have an access specifier
* I think the class must be a `@Injectable`, in this example, the `@Component` decorator provides this:

https://github.com/datenknoten/ngx-ssb-client/blob/83daec8a75fdf9e20eab28f9be78637057fefc4e/src/pages/public-feed/public-feed.component.ts#L85

I think an easy approach would be to allow to specify a function name which is exempted from this rule or maybe just the constructor as a boolean flag.

**Comment by stas-vilchik** [comment]
I think excluding a class constructor with parameter properties (possibly with a rule flag) should be sufficient.

**Comment by enko** [comment]
Thanks a lot for implementing this!
