### ISSUE TITLE
is sonarts incompatible with CodeClimate ?

### ISSUE THREAD

**Issue by abenhamdine** [SonarSource/SonarTS#653]
**I want to report a bug.**

when CodeClimate try to run tslint on pull requests, the following error occurs seemingly caused by Sonarts :  

```
/usr/src/app/node_modules/tslint/lib/configuration.js:55
        throw new error_1.FatalError("Failed to load " + configPath + ": " + error.message, error);
        ^

FatalError: Failed to load /tmp/codeclimate-tslint/735e9cb5198ddf117f6b296a88bb79a4596b106b4e90b0c7ad02387c23179ab7.json: Invalid "extends" configuration value - could not require "tslint-sonarts". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.
    at FatalError.Error (native)
    at new FatalError (/usr/src/app/node_modules/tslint/lib/error.js:27:28)
    at Object.findConfiguration (/usr/src/app/node_modules/tslint/lib/configuration.js:55:15)
    at new TsLinter (/usr/src/app/dist/tsLinter.js:33:57)
    at Object.<anonymous> (/usr/src/app/dist/index.js:26:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
```

**SonarTS version:** we use SonarTS bundled with SonarSource.sonarlint-vscode 1.3.0 <br>
**Node.js version:** 9.11<br>
**TypeScript version:** 2.8.3<br>

**SonarLint version and used IDE:** SonarSource.sonarlint-vscode 1.3.0<br>
**TSLint version:** TSLint 5.9.1 , tslint-language-service": "0.9.9<br>

**Expected behavior**

no error with CodeClimate

**Comment by vilchik-elena** [comment]
Hi,
I don't understand the scenario when you have failure. Could explain that better (keeping in mind me never worked with CodeClimate)?

- do you run SonarTS as tslint plugin?
- do you run SonarTS as SQ plugin?
- you provided the versions for everything, so I'm lost

**Comment by vilchik-elena** [comment]
- do you have failure running tslint locally?
- do you have failure running tslint with Codeclimate without sonarts?

**Comment by abenhamdine** [comment]
- No
- No

It seems to be a problem from CodeClimate, here is their answer : 

> Dave Henton (Code Climate)

>Jun 1, 12:03 PM EDT

>Hey Arnaud, 

>Thanks for writing in, and sorry about the trouble with this. I believe what's happening here is related to us not installing a repo's node_modules when running our plugins. For other repos where I've seen this pop up:

>when you run `npm install` locally to get a local `node_modules` directory containing the library (and then use our CLI to analyze your repo locally), you won't encounter this issue.

>The catch with that is we haven't figured out a good way to install the node_modules that are specified in a project that doesn't break aspects of the limits we place on engines for security reasons, and so it's going to take a bit more work on our side to map that work out and get it moving.

>Really sorry about the inconvenience with this in the meantime. I'd encourage you to reach out to the devs over at the Github repo for this engine. It looks like there are some dependencies they've included in the engine in order to support certain rules on Code Climate, so perhaps you could open a PR to get support for those modules you're using.

>In the meantime, you should be able to disable those rules which rely on NPM modules, and then see a successful analysis.

>Thanks,
>Dave

> Dave Henton, Support Specialist / Stay tuned to our Changelog for all the latest news: https://codeclimate.com/changelog and https://codeclimate.com/changelog.rss
