### ISSUE TITLE
Extend list of promise-like objects in AwaitPromise/S4123

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#659]
* WebElementPromise
* AxiosPromise
* Bluebird (Promise)

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/sonarlint/3zLQLLcw30o

To fix update the list here https://github.com/SonarSource/SonarTS/blob/master/sonarts-sq-plugin/sonar-typescript-plugin/src/main/java/org/sonar/plugin/typescript/rules/AwaitPromise.java#L30

Should we make this parameter configurable?...

**Comment by abenhamdine** [comment]
> Should we make this parameter configurable?...

I think so, many libraries could return Promise-like objects.

**Comment by andrea-guarino-sonarsource** [comment]
Another possible solution would be to check if an object is "Promise-like" at semantic level, so that we wouldn't need to add all the possible libraries.

**Comment by abenhamdine** [comment]
any news on this ?
because currently SonarTS is likely to be unusable for many users due to this issue...

**Comment by vilchik-elena** [comment]
@abenhamdine you can deactivate the rule in meantime

**Comment by abenhamdine** [comment]
I tried but for some reason, `"await-promise":false` in tslint.json has no effects.
The sonar-lint error is still shown, even after having restarted vs code.

**Comment by vilchik-elena** [comment]
@abenhamdine sonarlint has nothing to do with tslint.json config file. If you use SQ, deactivate rule there, if not, then, indeed, their is no way to activate rule yet.

**Comment by abenhamdine** [comment]
ah thx for the explanation.Indeed, I don't use SQ.
