### ISSUE TITLE
Capitalize ESLint rule titles

### ISSUE THREAD

**Issue by stas-vilchik** [SonarSource/SonarTS#667]
**I want to report a bug.**

**SonarTS version:** Latest
**SonarQube version:** 7.2

ESLint rule titles when display in SonarQube should be capitalized:

![image](https://user-images.githubusercontent.com/2317341/41837398-a2569656-785d-11e8-90d9-15c36bc815fc.png)

**Comment by vilchik-elena** [comment]
Won't fix due to #673
