### ISSUE TITLE
Analysis error "ts.unescapeIdentifier is not a function"

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarTS#668]
[tsutils](https://github.com/ajafff/tsutils) library, which is a dependency of tslint uses `ts.unescapeIdentifier` function from TypeScript. This function was removed, so we need to update the dependency to avoid errors with latest TypeScript versions. tsutils was fixed in https://github.com/ajafff/tsutils/pull/66

**Comment by vilchik-elena** [comment]
In TypeScript project
```
.../src/compiler/builder.ts TypeError: ts.unescapeIdentifier is not a function
```

**Comment by dlangerenken** [comment]
@m-g-sonar is this already available in the sonarqube-gradle-plugin?

**Comment by vilchik-elena** [comment]
@dlangerenken Do you mean scanner for gradle? Scanner doesn't embed language analyzers. It depends on SonarQube/SonarCloud you use with it, if SonarTS was updated there
