### ISSUE TITLE
Rule: Unused local variables should be removed

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarTS#67]
Implements [RSPEC-1481](https://jira.sonarsource.com/browse/RSPEC-1481)

**Comment by stas-vilchik** [comment]
This is covered by typescript's `--noUnusedLocals` compiler option

**Comment by fmallet** [comment]
Thanks for this notification @stas-vilchik. And same thing for unused private fields/functions. I'm closing won't fix this ticket.
