### ISSUE TITLE
sonarts-core not having lib/rules

### ISSUE THREAD

**Issue by vickyrocky** [SonarSource/SonarTS#672]
**"rulesDirectory": "./lib/rules" as mentioned in tslint-sonarts.json is not present. I am trying to modify this plugin and as per documentation i should add new rule in src/rules and tests in tests/rules but while doing ruling test, it's giving error and also while doing "yarn build-local " it's giving the same error like /lib is not there.So do we manually need to create this folder and put all the rules of src/rules inside that or am i missing something.Thanks in advance.**

**Comment by saberduck** [comment]
This folder is created automatically during the build. Can you send the output when you run `yarn build-local`?

**Comment by vickyrocky** [comment]
yarn build-local --can't find lib folder

**Comment by vickyrocky** [comment]
After changing the ide it's working fine now. It's weird but any how problem solved so closing this.
