### ISSUE TITLE
Support for TypeScript 3

### ISSUE THREAD

**Issue by kallaspriit** [SonarSource/SonarTS#686]
The library has TypeScript peer dependency:
`"typescript": "^2.2"`

This gives a warning with TypeScript v3+.
`warning "typestrict > tslint-sonarts@1.7.0" has incorrect peer dependency "typescript@^2.2".`

It still seems to work fine, perhaps the peer dependency could just be updated?

**Comment by stas-vilchik** [comment]
We'll do a set of tests with TypeScript 3 and then update the peer dependency. Thanks for the heads up!

**Comment by UselessPickles** [comment]
I started getting this error after upgrading my project to TypeScript 3.0:

> INFO: Sensor TypeScript Sensor [typescript]
> --
> ERROR: /Users/jlau/Development/PDS/web-app/node_modules/typescript/lib/typescript.js:1417
> ERROR:             throw e;
> ERROR:             ^
> ERROR:
> ERROR: Error: Debug Failure. Did not expect TypeParameter to have an Identifier in its trivia
> ERROR:     at addSyntheticNodes (/Users/jlau/Development/PDS/web-app/node_modules/typescript/lib/typescript.js:110825:30)
> ERROR:     at createChildren (/Users/jlau/Development/PDS/web-app/node_modules/typescript/lib/typescript.js:110814:9)
> ERROR:     at NodeObject.getChildren (/Users/jlau/Development/PDS/web-app/node_modules/typescript/lib/typescript.js:110758:56)
> ERROR:     at Object.toTokens (/Users/jlau/Development/PDS/web-app/.scannerwork/sonarts-bundle/node_modules/tslint-sonarts/lib/utils/navigation.js:115:35)
> ERROR:     at getHighlighting (/Users/jlau/Development/PDS/web-app/.scannerwork/sonarts-bundle/node_modules/tslint-sonarts/lib/runner/highlighter.js:27:33)
> ERROR:     at sensors.forEach.sensor (/Users/jlau/Development/PDS/web-app/.scannerwork/sonarts-bundle/node_modules/tslint-sonarts/lib/runner/tsrunner.js:58:57)
> ERROR:     at Array.forEach (native)
> ERROR:     at input.filepaths.map (/Users/jlau/Development/PDS/web-app/.scannerwork/sonarts-bundle/node_modules/tslint-sonarts/lib/runner/tsrunner.js:58:17)
> ERROR:     at Array.map (native)
> ERROR:     at processRequest (/Users/jlau/Development/PDS/web-app/.scannerwork/sonarts-bundle/node_modules/tslint-sonarts/lib/runner/tsrunner.js:53:34)

So I suspect that some changes are necessary to become compatibly with TS 3.0

**Comment by andrea-guarino-sonarsource** [comment]
Thank you for your feedback @UselessPickles, we will work on it soon.

**Comment by andrea-guarino-sonarsource** [comment]
@UselessPickles I didn't encounter any issue when upgrading some example projects to TS 3. Do you have any example code I can use to reproduce the issue?

**Comment by UselessPickles** [comment]
Unfortunately, this is a closed-source project, and I have no idea what to root cause is, so I can't produce a minimal repo.

**Comment by andrea-guarino-sonarsource** [comment]
As an update, we didn't manage to reproduce the issue by running the function that was causing the exception (i.e. `getHighlighting`) on a large set of files using TypeScript.
