### ISSUE TITLE
Rule: Identical expressions should not be used on both sides of a binary operator

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#7]
Implements RSPEC-1764

**Comment by stas-vilchik** [comment]
I suggest key `no-identical-expressions`

**Comment by inverno** [comment]
no-identical-sub-expressions maybe

**Comment by stas-vilchik** [comment]
rspec says "expressions"

**Comment by hosszubalazs** [comment]
Linking RSpec, you might want to add a sub-task for TypeScript: 
https://jira.sonarsource.com/browse/RSPEC-1764
