### ISSUE TITLE
Documentation of parameter headerFormat of  is misleading

### ISSUE THREAD

**Issue by Jidehem** [SonarSource/SonarTS#720]
**I want to provide the following feedback.**
The description of the parameter headerFormat is misleading.

We see currently: 
> Expected copyright and license header (without comment symbols). E.g. set 'COPYRIGHT' to match header '/*COPYRIGHT*/'. Regular expressions are supported.

Whereas it should be
> Expected copyright and license header (without comment symbols). E.g. set 'COPYRIGHT' to match header '/\*COPYRIGHT\*/'. Regular expressions are supported.
Probably that asterisks should be escaped as they seems to be interpreted (as I had to do to enter it in this issue...).

By the way, it may be good to add a precison about whether this parameter is always taken as a regular expression (in which case special characters like . (dot) or * (asterisk) should always be escaped)

**Rule key:** typescript:S1451

**Comment by andrea-guarino-sonarsource** [comment]
Hi @Jidehem,
This rule is based on TSLint rule [file-header](https://palantir.github.io/tslint/rules/file-header/).
Indeed, you're right: parameter is always interpreted as a regular expression, we will make it more explicit in the property description.
