### ISSUE TITLE
Cannot install sonarTS through update Center

### ISSUE THREAD

**Issue by kylezengTR** [SonarSource/SonarTS#727]
**I want to report a bug.**

**SonarTS version: 1.7** <br>

**SonarQube version: 6.0** <br>

**Expected behavior**

**I want to provide the following feedback.**
When I try to install the sonarTS from update Center, the version is 1.7, and after I clicked "install"
the following message pop out: 
```
Error while downloading plugin 'typescript' with version '1.7'. No compatible plugin found.
```

Please let me know if you need more details, thanks.

**Comment by vilchik-elena** [comment]
Your version of SQ is too old, update it

**Comment by kylezengTR** [comment]
@vilchik-elena  thanks for your reply, I think you can close this ticket. Thanks.,
