### ISSUE TITLE
How can I use my Quality Profile rules in TsLint-SonarTS plugin?

### ISSUE THREAD

**Issue by xxluke** [SonarSource/SonarTS#751]
**Question**
It's a very cool feature that it's possible to import the Sonar rules in TsLint, but I wonder what's the best way to make it only check the rules I have configurated on the Sonar server.

Is there a way to connect the TsLint plugin with the server? Or maybe a script or web-frontend to export the rules as JSON for tslint.json?

**Comment by vilchik-elena** [comment]
Hey, I see 2 ways of having same-rules-in-IDE-and-sonarqube
1.  If you use VSCode you can use SonarLint extension connected to your SQ server. It will pull rules activated there and show in VSCode only relevant issues

2. Configure sonar rules only in tslint.json, disable all rules in sonarqube. Import tslint issues with issues report (see doc https://docs.sonarqube.org/display/PLUG/Importing+TSLint+issues)

**Comment by andrea-guarino-sonarsource** [comment]
Closing this. Feel free to reopen if you need more clarifications.
