### ISSUE TITLE
Useless self assignment for array spread operator

### ISSUE THREAD

**Issue by DW8Reaper** [SonarSource/SonarTS#753]
I get a useless self assignment error when I use the spread operator to create a new array that contains the same items as the original. This is explicitly caught by this rule and is in the test suite below:
https://github.com/SonarSource/SonarTS/blob/d20daf2423a594920a18e8f2c37007c6eb61523e/sonarts-core/tests/rules/noSelfAssignmentRule/noSelfAssignmentRule.lint.ts#L44

I wonder about the value of this check since it is meaningful to create a new array with the same content in situations where I am doing change detection on the array reference and not the content. 

The other incarnations of the rule seem to catch logical errors where the user might think that a new array is created where in actual fact the original array is mutated. This particular case doesn't seem to fit that pattern.

**Comment by andrea-guarino-sonarsource** [comment]
Hi @DW8Reaper ,

> I wonder about the value of this check since it is meaningful to create a new array with the same content in situations where I am doing change detection on the array reference and not the content.

Could you please clarify on this with an example? are you talking about angular change detection?

Thanks,
Andrea

**Comment by DW8Reaper** [comment]
Hi Andrea,

One example would be angular change detection another that we get is with NGRX. So NGRX has a helper function createSelector, this will look at the incoming value and if it matches the previous value the function was called with it will return previous result instead of recalculating. My somewhat contrived example would be

```
  const itemList = [
    {name: 'a'},
    {name: 'b'}
  ];
  const firstEntry = createSelector(state, state => state[0].name)

  console.log(firstEntry(itemList));  // outputs: a
  
  itemList[0].name = 'f'; 
  console.log(firstEntry(itemList));  // outputs: a
```

So because the array reference didn't change the selector doesn't execute again even though the content did change. Not the best example but I could fix it by doing:

```
  const itemList = [
    {name: 'a'},
    {name: 'b'}
  ];
  const firstEntry = createSelector(state, state => state[0].name)

  console.log(firstEntry(itemList));  // outputs: a
  
  itemList[0].name = 'f';
  itemList = [...itemList];
  console.log(firstEntry(itemList));  // outputs: f
```

I hope that makes sense.

**Comment by biohazard999** [comment]
I've got the same issue:
We use aurelia's binding and need to make an copy of the array to trigger rebinding

```ts
export interface Element {
   elements: ElementItem[];
}
export interface ElementItem {
  value: string;
}

export class MyViewModel {
   public element: Element;

   // bound to element.elements
   public elements: ElementItems[] = [];

   public elementChanged() {
    this.elements = [...this.elements]; //This ensures we get a copy after binding happens, so we don't  change this.element.elements array directly or by mistake
  }

  /* More code to modify elements before writing back to element.elements */
}

```
Hope that makes sense as well.

**Comment by andrea-guarino-sonarsource** [comment]
Hi @DW8Reaper and @biohazard999 ,
Thank you for your feedbacks and examples.
#760 has been created to handle this.
