### ISSUE TITLE
Rule type-checker independent version of no-unused-variable

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#76]
There is no-unused-variable from tslint core which is base on compiler option (not part of default profile). May be for users it would be valuable to have the same rule but not using type-checker. 
To validate this idea we have look through some regular projects using tslint and see if they enabled that rule.

**Comment by inverno** [comment]
It's not in the recommended tslint profile because it is deprecated (due to the presence of the compiler option) : https://github.com/palantir/tslint/issues/1481

**Comment by vilchik-elena** [comment]
Covered by compiler options -> closed as won't fix
