### ISSUE TITLE
Can we generate multiple test "reports" in SonarQube

### ISSUE THREAD

**Issue by naithagoni** [SonarSource/SonarTS#767]
I have two questions regarding SonarQube.

1. Currently, I can successfully generate the report for "Unit tests" of my angular6 and typescript based application but I want to also generate reports for "Integration test" and "e2e test" for the same project. I have researched but did not get the proper answers.

2. I have generated the "Unit test" report but it is showing "0" vulnerabilities (I am sure, there are vulnerabilities in my application but not showing instead showing "0"). I have googled it, there are some discussions that, I have to write some "security-related-rules (don't understand)". Could anybody please explain? (any examples?)

**sonar-project.properties:**

sonar.host.url=http://localhost:9000
sonar.projectKey=jest-sonar-reporter
sonar.projectName=myReport
sonar.description=Angular SPA Frontend
sonar.projectVersion=7.3
sonar.sources=src/app
sonar.exclusions=node_modules/**,**/dev/**,**/*.js,**/*.vb,**/*.css,**/*.scss
sonar.tests=src/app
sonar.test.inclusions=**/*.unit.spec.ts
sonar.testExecutionReportPaths=reports/test-reporter.xml
sonar.genericcoverage.unitTestReportPaths=reports/test-reporter.xml

**package.json**

"jest": {
    "preset": "jest-preset-angular",
    "setupTestFrameworkScriptFile": "<rootDir>/src/setup-jest.ts",
    "testResultsProcessor": "jest-sonar-reporter"
  },
  "jestSonar": {
    "reportPath": "reports",
    "reportFile": "test-reporter.xml",
    "indent": 4
  }

**Comment by vilchik-elena** [comment]
Please create new issue using our template for 1 problem you have
