### ISSUE TITLE
I am unable to generate coverage report for tslint using sonarTs

### ISSUE THREAD

**Issue by philipsSdk** [SonarSource/SonarTS#775]
My Karma config looks like:
reporters: ['progress', 'coverage', 'sonarqubeUnit'],

sonarQubeUnitReporter: {
  sonarQubeVersion: 'LATEST',
  outputFile: '.tmp/sonarQube/coverage/test-report.xml',
  useBrowserName: false
},

// optionally, configure the reporter
coverageReporter: {
  type : 'lcov',
  dir : './.tmp/sonarQube/coverage',
  check: {
    global: {
      statements: 75,
      branches: 50,
      functions: 100,
      lines: 10
    },
    each: {
      statements: 75,
      branches: 50,
      functions: 100,
      lines: 10,
    }
  },
  watermarks: {
    statements: [ 50, 75 ],
    functions: [ 50, 100 ],
    branches: [ 25, 50 ],
    lines: [ 10, 55 ]
  }
},
karmaTypescriptConfig: {
reports:
{
"lcovonly": {
"directory": ".tmp/sonarQube/coverage",
"filename": "lcov.info",
}
},}

Sonar.project.properties:
sonar.projectVersion=1.8.0
sonar.ts.tslintconfigpath=tslint.json
sonar.sources=src
sonar.tests=src
sonar.sourceEncoding=UTF-8
sonar.ts.excludetypedefinitionfiles=true
sonar.exclusions=/node_modules/, /dependencies//.js,**/release/,/release//.js
sonar.ts.tslint.path=/node_modules/tslint/bin/tslint
sonar.test.inclusions=src/core//.spec.ts, src/providers///*.spec.ts
sonar.typescript.lcov.reportPaths=.tmp/sonarQube/coverage/lcov.info
sonar.testExecutionReportPaths=.tmp/sonarQube/coverage/test-report.xml
sonar.typescript.tslint.reportPaths=.tmp/sonarQube/tslint-report.json

Analysis runs succesfuly and lcov.info generated but sonar fails to update coverage report
Coverage reports shows 0%

**Comment by philipsSdk** [comment]
My Karma config looks like:
reporters: ['progress', 'coverage', 'sonarqubeUnit'],

    sonarQubeUnitReporter: {
      sonarQubeVersion: 'LATEST',
      outputFile: '.tmp/sonarQube/coverage/test-report.xml',
      useBrowserName: false
    },
    

    // optionally, configure the reporter
    coverageReporter: {
      type : 'lcov',
      dir : './.tmp/sonarQube/coverage',
      check: {
        global: {
          statements: 75,
          branches: 50,
          functions: 100,
          lines: 10
        },
        each: {
          statements: 75,
          branches: 50,
          functions: 100,
          lines: 10,
        }
      },
      watermarks: {
        statements: [ 50, 75 ],
        functions: [ 50, 100 ],
        branches: [ 25, 50 ],
        lines: [ 10, 55 ]
      }
    },
 karmaTypescriptConfig: {
      reports:
      {
        "lcovonly": {
          "directory": ".tmp/sonarQube/coverage",
          "filename": "lcov.info",
        }
      },}



Sonar.project.properties:
sonar.projectVersion=1.8.0
sonar.ts.tslintconfigpath=tslint.json
sonar.sources=src
sonar.tests=src
sonar.sourceEncoding=UTF-8
sonar.ts.excludetypedefinitionfiles=true
sonar.exclusions=**/node_modules/**, **/dependencies/**/*.js,**/release/*,**/release/**/*.js
sonar.ts.tslint.path=**/node_modules/tslint/bin/tslint
sonar.test.inclusions=src/core/**/*.spec.ts, src/providers/**/**/*.spec.ts
sonar.typescript.lcov.reportPaths=.tmp/sonarQube/coverage/lcov.info
sonar.testExecutionReportPaths=.tmp/sonarQube/coverage/test-report.xml
sonar.typescript.tslint.reportPaths=.tmp/sonarQube/tslint-report.json


Coverage reports shows 0%

**Comment by vilchik-elena** [comment]
Please follow issue template when creating issue
Closing this one
