### ISSUE TITLE
False positive: no-useless-cast

### ISSUE THREAD

**Issue by dimascyriaco** [SonarSource/SonarTS#779]
I want to report a bug.

SonarTS version: 1.8.0
Node.js version: 10.14.1
TypeScript version: 3.2.1

Rule key: no-useless-cast

Reproducer

![not-null-assertion](https://user-images.githubusercontent.com/65256/49880964-598cc980-fe14-11e8-85e4-0076482f5404.png)

Expected behavior

This should not be pointed as a `unnecessary not-null assertion`, because the value can be undefined.

**Comment by vilchik-elena** [comment]
@dimascyriaco Thanks for reporting! unfortunately it's hard to guess the root of the problem from the code provided by you. Could you show `minimumCharacters` declaration and further actions on it?
Also typescript compiler options will be helpful.

**Comment by dimascyriaco** [comment]
It was a React component prop with a default value of `0`. And this was the first usage of this value.

But I'm not having this problem anymore. Fell free to close this issue.

Thanks.

**Comment by ajmath** [comment]
I'm seeing a number of these types of issues with a project that was recently imported into SonarQube

typescript 3.2.1
local-node: 8.10
jenkins-node: ?
SonarQube: 7.4 Developer edition
scanner: sonar-3.2.0.1227

The scan is being run as a part of my companies CI pipeline and I don't currently have much control over that environment so I'm not sure what node version is running.

Here is what the errors presented in SonarQube look like:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/266679/51689279-587aba80-1fc4-11e9-9187-f417dc797c00.png">

And here is what Webstorm tells me when I try to remove the cast:
![image](https://user-images.githubusercontent.com/266679/51689337-79431000-1fc4-11e9-8e85-33184eb2e9ff.png)

I'm seeing similar issues as the one reported with some react component props that I can share later once I have a chance to extract the relevant bits.

**Comment by ajmath** [comment]
@vilchik-elena Can you provide any insight into why we're seeing these false positives?

**Comment by vilchik-elena** [comment]
@ajmath Could you open a new issue as your problem is not related to this issue?
