### ISSUE TITLE
Question: noUnusedLocal vs no-dead-store

### ISSUE THREAD

**Issue by f0rr0** [SonarSource/SonarTS#780]
What is the difference between using the compiler option `noUnusedLocal` and using the lint-rule `no-dead-store`?

Is there a case where the latter throws an error while the former doesn't or vice-versa?

**Comment by andrea-guarino-sonarsource** [comment]
Hi @f0rr0,
`no-dead-store` rule is also capable to catch useless assignments when values are overwritten like the following:

```typescript
function func() {
  var x = 3; // dead store
  x = 5;
  console.log(x); 
}
```

Here `x` is actually used, however the initialisation done on the first line of `func` is useless since its value is overwritten without being ever read.
