### ISSUE TITLE
SonarQube how to set tsconfig.json property

### ISSUE THREAD

**Issue by MlleBeuze** [SonarSource/SonarTS#803]
Hi all,

**I want to report a bug.**

**SonarTS version:** 1.8<br>
**Node.js version:** 8.12.0<br>
**TypeScript version:** 2.7.2<br>

**SonarQube version:** 7.1.0<br>

**Rule key:** "Dependencies should be explicit"

**Reproducer** 
![image](https://user-images.githubusercontent.com/13280573/51329475-dba48980-1a75-11e9-84d5-937b6d0f2b7d.png)

**Logs**
```
"Module '@shared/.....component.ts' is not listed as dependency in package.json." 
```

**Expected behavior**
All the Code Smells should be gone as we specified where is the tsconfig.json, but they're still there.

**More explanations:**
We tried to specify the tsconfig.json in the configuration in the "sonar.typescript.tsconfigPath" emplacement, as you can see on the attached file. Our tsconfig.json file is at the root /tsconfig.json and it's where we defined all the alias paths.

But when we run SonarQube again, the related Code Smells are still there. Where are we wrong?

Thank you for your help!

**Comment by vilchik-elena** [comment]
Hello @MlleBeuze,

Please provide following info to help your with your problem:
* Logs of analysis (output of "sonar-scanner")
* Content of your tsconfig
* Precise issue message (as I don't think you have 5 dots in your module name/path)

**Comment by sashless** [comment]
We get the same error. It seems to miss support for multiple `package.json` which are used in `yarn workspaces`

**Comment by vilchik-elena** [comment]
@sashless this rule is a wrap of TSLint's `no-implicit-dependencies`. And indeed if you read [rule implementation](https://github.com/palantir/tslint/blob/master/src/rules/noImplicitDependenciesRule.ts) they find closest `package.json` file and check dependencies there. 
So one way to go is to ask TSLint to support `yarn workspaces` (and I would consider this more as a new feature then as a bug).
For the time being you can configure a big whitelist for this rule or disable it at all.

**Comment by fabianedl777** [comment]
@vilchik-elena I configure this white list in my tslint.config file but when I send my typescript files to sonarqube it shows me again this rule in sonarqube where is this white list configured so that it doesn't show me this in sonarqube?

Thank you.

**Comment by vilchik-elena** [comment]
@fabianedl777 when used with SonarQube you should configure whitelist in the SQ rule profile, tslint configuration is ignored
