### ISSUE TITLE
Remove security hotspot rules from default profiles for old versions of SonarQube

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#827]
To do that use `SonarRuntime`-aware `load` method. See https://github.com/SonarSource/sonar-analyzer-commons/blob/df9b31a81a9997f7193e61709a2f3973d2584188/commons/src/main/java/org/sonarsource/analyzer/commons/BuiltInQualityProfileJsonLoader.java#L52

**Comment by saberduck** [comment]
This is no longer relevant, plugin is using SQ 7.9 as min version. See #874
