### ISSUE TITLE
Moving to ESLint and TSLint deprecation

### ISSUE THREAD

**Issue by cafesanu** [SonarSource/SonarTS#832]
**I want to request a feature.**

Given the TS 2019 roadmap (https://github.com/Microsoft/TypeScript/issues/29288) and the future deprecation of TSLint (https://github.com/palantir/tslint/issues/4534), I'm wondering if there will be any work in this library to transfer any TSLint rules that still do not exist in ESLint to ESLint.

Thanks

**Comment by vilchik-elena** [comment]
See this thread https://github.com/SonarSource/SonarTS/issues/825

**Comment by vilchik-elena** [comment]
Duplicates #825
