### ISSUE TITLE
Provide a whitelist for (false/positive) Module '@workspace/shared' is not listed as dependency in package.json (typescript:S4328)

### ISSUE THREAD

**Issue by appsolutegeek** [SonarSource/SonarTS#848]
How do you provide a whitelist for the following rule ?

Module '@workspace/shared' is not listed as dependency in package.json (typescript:S4328)

I notice its here, in the java file

https://github.com/SonarSource/SonarTS/blob/0bac2c4253dcad38489025ca5fd4a70a9d9babfa/sonarts-sq-plugin/sonar-typescript-plugin/src/main/java/org/sonar/plugin/typescript/rules/NoImplicitDependencies.java

but how do you control the whitelist, i noticed a test xml file also.

I want to add @worksapce as a valid whitelist, so that the following rule is ignored.

I can't find anything in sonar plugin section.

Is there a document that states how to add to the whitelist of a rule ?

Thanks in advance

**Comment by appsolutegeek** [comment]
I looked in the Rulse section of sonar and i see a property WhiteList, but how do I edit it ? Maybe I have to be an admin ? Is it possible to edit via the sonar ui ?

**Comment by vilchik-elena** [comment]
Indeed you should have admin rights, then you will be able to edit it through UI (and that's the only way to edit it)

**Comment by appsolutegeek** [comment]
Thanks @vilchik-elena , yes we managed to do it. Although we had to clone the profile first.

**Comment by chrisaddams** [comment]
Hey, how did you specify this? I'm having the same issue. One of the following?
`@` `@/` `@/*`

**Comment by karlismelderis** [comment]
I'm nor sure if reply is good enough.
each our project has different setup and altering global config to add all possible options sound like overkill.
I think you should honor tsconfig.json here

**Comment by iangregsondev** [comment]
@chrisaddams Hi, you have to create a new profile from the default and then you can override settings. It's not great to tell you the truth - but it works.

Personally I think SONAR should understand the tspaths in the tsconfig
