### ISSUE TITLE
Branch anaylsis for angular

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [SonarSource/SonarTS#865]
I want to confirm if there is any branch analysis feature available for angularjs project in sonarqube?

**Comment by vilchik-elena** [comment]
This feature does not depend on the language. It's available since developer edition, see [these docs](https://docs.sonarqube.org/latest/branches/overview/).

**Comment by beena-yatin-kanyal** [comment]
@vilchik-elena - We are not able to show different branches in project dropdown of the angular project as angular project does not have pom.xml

**Comment by vilchik-elena** [comment]
who is talking about pom.xml? 
Anyway I close this issue as not relevant to this repository. Please open a new thread at https://community.sonarsource.org
