### ISSUE TITLE
Setting for rule S4328 whitelist parameter in sonar-project.properties.

### ISSUE THREAD

**Issue by tommywo** [SonarSource/SonarTS#873]
**I want to request a feature.**
Setting for rule S4328 whitelist parameter in sonar-project.properties.

Currently is only possible to set whitelist in Quality Profile. We use shared profile, so setting it globally for one project would cause false negatives in different projects. We would like to set it on project basis. 

**Rule key:** S4328

**Comment by saberduck** [comment]
You can configure Quality Profile per project. Anyway, I would suggest opening a topic on https://community.sonarsource.com/, because this is not SonarTS specific request.
