### ISSUE TITLE
typescript:S4798 in abstract classes / functions

### ISSUE THREAD

**Issue by Franziskus1988** [SonarSource/SonarTS#890]
**I want to report a bug.**

**SonarTS version:** 5.14 (build 18788)<br>
**Node.js version:** v10.14.1 <br>
**TypeScript version:** 3.5.2<br>

**SonarQube version:** 7.9.1.27448<br>
**SonarLint version and used IDE:** 1.12.0 VSCode<br>

**Rule key:** typescript:S4798

**Error:**
Sonarlint shows this warning:
<img width="1217" alt="sonar_warning" src="https://user-images.githubusercontent.com/5774027/69794372-6d1e7500-11ca-11ea-87a0-e79648732d06.png">

But you can't set the value in a abstract class:
<img width="614" alt="tsc_error" src="https://user-images.githubusercontent.com/5774027/69794426-86272600-11ca-11ea-89e8-5a7caec09977.png">

**Expected behavior**
Think it's a false positive.

**Comment by vilchik-elena** [comment]
Thanks for reporting! I created an issue in SonarJS project https://github.com/SonarSource/SonarJS/issues/1768 (now TS analysis is performed by SonarJS)
