### ISSUE TITLE
Rule 5604 Using intrusive permissions is security-sensitive

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [SonarSource/SonarTS#892]
Implements https://jira.sonarsource.com/browse/RSPEC-5604

Code examples: https://github.com/SonarSource/security-expected-issues/tree/master/javascript/hotspots/RSPEC-5604

**Comment by saberduck** [comment]
hello @eric-therond-sonarsource , we don't develop new rules in this plugin. TypeScript analysis was migrated to SonarJS.
