### ISSUE TITLE
 can you please let us know 

### ISSUE THREAD

**Issue by Pooja123-gp** [SonarSource/SonarTS#901]
@saberduck  can you please let us know 

Expected release date of ESLint-SonarTS?
Expected depreciation date of TSLint-SonarTS ?

_Originally posted by @Pooja123-gp in https://github.com/SonarSource/SonarTS/issues/825#issuecomment-591242145_

**Comment by saberduck** [comment]
tslint-sonarts is already deprecated, there will be no more releases.

New analyzer based on eslint is now available as part of SonarQube 7.9 LTS or SonarQube 8.2, respectively on https://sonarcloud.io/
