### ISSUE TITLE
404 page on the doc of npm

### ISSUE THREAD

**Issue by mrdulin** [SonarSource/SonarTS#905]
I am reading [Code Smell Detection](https://www.npmjs.com/package/tslint-sonarts/v/1.8.0#code-smell-detection-pig) section of doc on npm: 

When I click the link about `no-dead-store`, it gives me a 404 page. Here is the page: https://github.com/SonarSource/SonarTS/blob/HEAD/sonarts-core/docs/rules/no-dead-store.md

**Comment by vilchik-elena** [comment]
Hey,

This project is deprecated, indeed some links are broken now, I don't think we will fix them

For the reference `no-dead-store` rule should be moved into eslint-plugin-sonarjs in next version (https://github.com/SonarSource/eslint-plugin-sonarjs/issues/48)

**Comment by vilchik-elena** [comment]
I deprecated the package in npm to make it explicit
