### ISSUE TITLE
Typescript 3.7.2 Null conditional operator on a function call is giving a false positive

### ISSUE THREAD

**Issue by kramdass08** [SonarSource/SonarTS#908]
Analyzing typescript application with Community EditionVersion 7.9.4 (build 35981)LGPL v3 flags "Expected an assignment or function call and instead saw an expression" as Bug. This is identified as a bug with SonarCloud Typescript: 3.7.2. Please find the reference below, 
https://community.sonarsource.com/t/typescript-3-7-2-null-conditional-operator-on-a-function-call-is-giving-a-false-positive/17791
Please review and let us know if there are patch/fix to resolve the above bug.

**Comment by saberduck** [comment]
hello,
this bug will not be fixed in the LTS 7.9.x version of SonarQube. You can upgrade to current (non-LTS) version 8.4, or you will need to wait for the next LTS version (planned for early 2021).
