### ISSUE TITLE
Calculate Cyclomatic Complexity metric

### ISSUE THREAD

**Issue by inverno** [SonarSource/SonarTS#99]

**Comment by fmallet** [comment]
Relates to #100

**Comment by devuo** [comment]
Is this feature still in the roadmap?

**Comment by vilchik-elena** [comment]
@devuo yep, are you interested?

**Comment by devuo** [comment]
@vilchik-elena yep, in my company most teams use JS and it's one of the metrics we look at in terms of Quality Engineering. My team has adopted TypeScript recently and we're missing this one metric.

**Comment by vilchik-elena** [comment]
@devuo Ok, thanks for info! good to know that when building backlog for next version.
FYI you can always "vote" for issues you are interested in by ["reacting"](https://help.github.com/articles/about-discussions-in-issues-and-pull-requests/#reacting-to-ideas-in-issues-and-pull-requests) to the top comment.
And don't hesitate to create new issues if you don't find the feature your are interested in.

**Comment by Talento90** [comment]
CCM for TypeScript is must have feature! Looking forward to see it in the next version! 👍
My company and I are really interested in this metric for quality reports!

**Comment by joaoTavare** [comment]
I am also interested!! 👍

**Comment by devuo** [comment]
Yeah 💯
